Validate data refactor
openprocurement/openprocurement.api pull request #436
Opened 2019-04-15 12:59 UTC by bdmbdsm

2019-04-17 07:56 UTC, oleksiyVeretiuk approved these changes

2019-04-17 08:06 UTC, oleksiyVeretiuk commented on src/openprocurement/api/utils/data_engine.py
> +        """Applies event.data on event.context and returns applied data wrapped into invalid model
Чого модель invalid, якщо в неї записуються, щойно провалідовані дані?

2019-04-17 08:08 UTC, oleksiyVeretiuk commented on src/openprocurement/api/utils/data_engine.py
> +        method = updated_model.to_patch
Чи вартує цей метод виносити в окрему змінну? Він не є статичним, а тому щільно прив'язаний до об'єкта, ну й + до того на мою думку зменшується читабельність коду

2019-04-18 14:21 UTC, bdmbdsm commented on src/openprocurement/api/utils/data_engine.py
> +        """Applies event.data on event.context and returns applied data wrapped into invalid model
Уважно читаєш) :+1: 

Після накладання даних які прислав користувач на дані з БД треба пропустити результат накладання через роль. Ця фільтрація і відкидає недозволені для редагування поля. Тобто, якщо на результаті пропускання моделі через `edit_...` роль викликати `validate()`, то дуже ймовірно, що дані будуть невалідними, бо `edit` точно відкине такі поля як `id`, 'owner_token` і їм подібні.

Але та невалідна модель служить джерелом даних для бізнес-логіки. До рефактору вона жила в `request.validated['auction']`. Відповідно, дані, з якої модель створена - в `request.validated['data']`.

2019-04-18 14:23 UTC, bdmbdsm commented on src/openprocurement/api/utils/data_engine.py
> +        method = updated_model.to_patch
Згоден. Я скопіпастив і якось не виправив.

2019-04-19 06:37 UTC, bdmbdsm commented on src/openprocurement/api/utils/data_engine.py
> +        method = updated_model.to_patch
Виправив

2019-04-19 07:26 UTC, oleksiyVeretiuk commented on src/openprocurement/api/utils/data_engine.py
> +        """Applies event.data on event.context and returns applied data wrapped into invalid model
Я так поняв в low_ctx зберігаються неповні дані після цього методу правильно?
Тобто там будуть лише ті поля, які користувач може редагувати так?

2019-04-22 14:10 UTC, Scandie requested changes

2019-04-22 14:10 UTC, Scandie commented on src/openprocurement/api/utils/ownership.py
> +                self.m.transfer_token = transfer_token
@bdmbdsm, можливо, щось упускаю, але тут не повинен бути хешований токен?

2019-04-22 14:10 UTC, Scandie commented on src/openprocurement/api/validation.py
> +def validate_json_data(request, leave_json_data_into_request=True):
Не зовсім очевидина назва аргумента. Мається на увазі, залишити `json_data` в запиті?

2019-04-22 14:10 UTC, Scandie commented on src/openprocurement/api/utils/data_engine.py
> +        This issue could be solved by applying filtered data on the data on the untouched data
Маленька дуплікаця.

2019-04-22 14:10 UTC, Scandie commented on src/openprocurement/api/utils/logging_context.py
> +    def set_item(self, key, value, add_prefix=True):
@bdmbdsm, прапорець `add_prefix` - бачу, а перевірка є?

2019-04-23 08:55 UTC, bdmbdsm commented on src/openprocurement/api/utils/ownership.py
> +                self.m.transfer_token = transfer_token
Код для цього класу я брав [звідси](https://github.com/openprocurement/openprocurement.api/blob/a453312b08881c4056fc7ee54b6964a7514870cb/src/openprocurement/api/utils/common.py#L195). В тому методі є можливість прямого встановлення токена, а є й хешованого. Тут я повторив як було, тільки трошки порефакторив: виніс самостійні куски коду в окремі методи.

2019-04-23 08:55 UTC, bdmbdsm commented on src/openprocurement/api/validation.py
> +def validate_json_data(request, leave_json_data_into_request=True):
Так, це і мається на увазі. Як би ти назвав цей аргумент?

2019-04-23 08:55 UTC, bdmbdsm commented on src/openprocurement/api/utils/logging_context.py
> +    def set_item(self, key, value, add_prefix=True):
Дякую за уважність) недогледів.

2019-04-23 08:55 UTC, bdmbdsm commented on src/openprocurement/api/utils/data_engine.py
> +        This issue could be solved by applying filtered data on the data on the untouched data
Не зрозумів :eyes:

2019-04-23 08:57 UTC, bdmbdsm commented on src/openprocurement/api/utils/data_engine.py
> +        """Applies event.data on event.context and returns applied data wrapped into invalid model
Неповні дані зберігаються в `event.ctx.cache.low_data_model`. В `event.ctx.low` зберігається модель даних, вичитаних з БД.

2019-04-23 10:11 UTC, Scandie commented on src/openprocurement/api/validation.py
> +def validate_json_data(request, leave_json_data_into_request=True):
`keep_json_data_in_request` чи щось таке.

2019-04-23 10:13 UTC, Scandie commented on src/openprocurement/api/utils/data_engine.py
> +        This issue could be solved by applying filtered data on the data on the untouched data
>>`applying filtered data on the data on the untouched data`  :upside_down_face:

2019-04-23 10:22 UTC, bdmbdsm commented on src/openprocurement/api/validation.py
> +def validate_json_data(request, leave_json_data_into_request=True):
Перейменував :+1:

2019-04-23 10:38 UTC, Scandie approved these changes

2022-12-20 07:52 UTC, closed without merging